server:
  port: ${PORT:8082}

spring:
  application:
    name: buscador
  main:
    allow-bean-definition-overriding: true
  elasticsearch:
    uris: https://elasticsearch-production-76d4.up.railway.app

eureka:
  client:
    service-url:
      defaultZone: https://eureka-server-production-6564.up.railway.app/eureka/
